//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cute.Squirrel.App.Daemon.ConsoleDemo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class DaemonSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DaemonSettings defaultInstance = ((DaemonSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DaemonSettings())));
        
        public static DaemonSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TribeAddress {
            get {
                return ((string)(this["TribeAddress"]));
            }
            set {
                this["TribeAddress"] = value;
            }
        }
    }
}
